export const FETCH_USER_PROFILE_START = '@user/FETCH_USER_PROFILE_START';
export const FETCH_USER_PROFILE_SUCCESS = '@user/FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILED = '@user/FETCH_USER_PROFILE_FAILED';
export const ON_LOGOUT = '@user/ON_LOGOUT';
